=== GrinUA/epamfinal/epamTasks/out/artifacts/unnamed/ua/nure/uvarov/Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

        <xsd:element name="Diamonds">
            <xsd:complexType mixed="true">
                <xsd:sequence >
                    <xsd:element name="Gem" type="Gem" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>

    <xsd:complexType name="Gem" mixed="true">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Preciousness" type="preciousness"/>
            <xsd:element name="Origin" type="xsd:string"/>
            <xsd:element name="Colour" type="xsd:string"/>
            <xsd:element name="Transparency" type="transparency"/>
            <xsd:element name="Edges" type="edges"/>
            <xsd:element name="Value" type="value"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="preciousness">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Precious"/>
            <xsd:enumeration value="Semiprecious"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="transparency">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="100"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="edges">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="4"/>
            <xsd:maxInclusive value="15"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="value">
        <xsd:restriction base="xsd:double">
            <xsd:minInclusive value="0.01"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== GrinUA/epamfinal/epamTasks/out/production/epamTasks/ua/nure/uvarov/Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->
<Diamonds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="input.xsd">>
    <Gem>
        <Name>Akbar Shah</Name>
        <Preciousness>Precious</Preciousness>
        <Origin>India</Origin>
        <Colour>Colorless</Colour>
        <Transparency>10</Transparency>
        <Edges>5</Edges>>
        <Value>71.7</Value>>
    </Gem>

    <Gem>
        <Name>Allnatt Diamond</Name>
        <Preciousness>Precious</Preciousness>
        <Origin>South Africa</Origin>
        <Colour>Yellow</Colour>
        <Transparency>50</Transparency>
        <Edges>4</Edges>>
        <Value>101.29</Value>>
    </Gem>

    <Gem>
        <Name>Hope</Name>
        <Preciousness>Semiprecious</Preciousness>
        <Origin>USA</Origin>
        <Colour>Yellow</Colour>
        <Transparency>10</Transparency>
        <Edges>5</Edges>>
        <Value>5</Value>>
    </Gem>
</Diamonds>
